version: "3.9"
services:
  app:
    container_name: app
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - "APP_PORT=${APP_PORT}"
      - "APP_SECRET=${APP_SECRET}"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_NAME=${DB_NAME}"
      - "DB_ADMIN_USER=${DB_ADMIN_USER}"
      - "DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}"
      - "DB_CLIENT_USER=${DB_CLIENT_USER}"
      - "DB_CLIENT_PASSWORD=${DB_CLIENT_PASSWORD}"
      - "DB_POOL_MAX=${DB_POOL_MAX}"
    depends_on:
      - db


  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - "./db.sql:/docker-entrypoint-initdb.d/db.sql"
    environment:
      - "POSTGRES_PASSWORD=${DB_ADMIN_PASSWORD}"
